.IGNORE:
all:
	gcc fin01.c bmp.c bmp.h -o fin01 -lm 
	gcc fin02.c bmp.c bmp.h -o fin02 -lm -lcurl
	gcc fin03.c database.h database.c -w -o fin03 -lm
clear:
	rm fin01
	rm fin02
	rm fin03
	rm *.bmp
	