.IGNORE:
all:

	gcc hw0101.c mystring.h mystring.c -o hw0101 -lm
	gcc hw0102.c mycal.h mycal.c -o hw0102 -lm 
	gcc hw0103.c mychain.h mychain.c -o hw0103 -lm 
	gcc hw0104.c mymaze.h mymaze.c -o hw0104 -lm
	gcc hw0105.c -o hw0105 -lm