.IGNORE:
all:
	gcc mid01.c myinclude.h  -o mid01 -lm
	gcc mid02.c myinclude.h -o mid02 -lm
	gcc mid03.c myinclude.h AndyLuBMP.h AndyLuBMP.c -o mid03 -lm
	gcc mid04.c myinclude.h AndyLuBMP.h AndyLuBMP.c -o mid04 -lm